dist: trusty
sudo: required

git:
  depth: 1

cache: pip
language: python

env:
    - DB=sqlite
    - DB=sqlite DB_EXTENSION=gis
    - DB=mysql
    - DB=mysql DB_EXTENSION=gis
    - DB=postgres DB_VERSION=9.3
    - DB=postgres DB_VERSION=9.4
    - DB=postgres DB_VERSION=9.5
    - DB=postgres DB_VERSION=9.6
    - DB=postgres DB_VERSION=9.3 DB_EXTENSION=gis
    - DB=postgres DB_VERSION=9.4 DB_EXTENSION=gis
    - DB=postgres DB_VERSION=9.5 DB_EXTENSION=gis
    - DB=postgres DB_VERSION=9.6 DB_EXTENSION=gis
    - DB=mariadb DB_VERSION=10.0
    - DB=mariadb DB_VERSION=10.1
    - DB=mariadb DB_VERSION=10.2
    - DB=mariadb DB_VERSION=10.0 DB_EXTENSION=gis
    - DB=mariadb DB_VERSION=10.1 DB_EXTENSION=gis
    - DB=mariadb DB_VERSION=10.2 DB_EXTENSION=gis

python:
 - 3.4
 - 3.5
 - 3.6

install:
    - export DJANGO_SETTINGS_MODULE=test_${DB}

    - travis_retry pip install --upgrade pip tblib wheel

    - if [ ${DB} == "postgres" ]; then
        sudo service postgresql stop;
        sudo service postgresql start ${DB_VERSION};
        travis_retry pip install psycopg2 --upgrade;

        if [ -v DB_EXTENSION ]; then
            psql -U postgres -c "create extension ${DB_EXTENSION}";
        fi;
      fi

    - if [ ${DB} == "mysql" ]; then
        sudo service mysql start || true;
        travis_retry pip install mysqlclient --upgrade;
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql;
      fi

    - if [ ${DB} == "mariadb" ]; then
        sudo service mariadb start ${DB_VERSION} || true;
        travis_retry pip install mysqlclient --upgrade;
      fi

    - if [ -v DB_EXTENSION ]; then
        export DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}_${DB_EXTENSION};
      fi

    - if [ ${DB_EXTENSION} == "gis" ]; then
        sudo apt install libspatialite5 spatialite-bin binutils libproj-dev gdal-bin libspatialite-dev -qq;
      fi

script:
    - travis_retry python setup.py develop
    - cd tests/
    - echo settings=$DJANGO_SETTINGS_MODULE
    - df -h
    - PYTHONUNBUFFERED=1 python runtests.py --parallel=4

after_failure:
    - df -h

notifications:
  email: false
